[package]
name = "pic_emulator_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.0"
tokio = "1.44.2"
common = { path = "../common" }